# the DisableItems configuration file

# send when player try to use totem
totem-disable-message: "ยง4Totem is disabled on this server!"

# send when player try to use elytra
elytra-disable-message: "ยง4Elytra is disabled on this server!"